package com.adeptpros.digipass.utility;

public class HtmlEmailBody {
	/*public String email="<div id=\":fz\" class=\"a3s\" style=\"overflow: hidden;\"><div class=\"adM\"></div><u></u><div style=\"color:#000;font-size:100%;font-family:'Arial';line-height:1.65;width:100%!important;min-height:100%;margin:0;padding:0\">";
	email=email+"<table style=\"font-size:100%;font-family:'Arial';line-height:1.65;width:100%!important;height:100%;background:#fff;margin:0;padding:0\" bgcolor=\"#fff\"><tbody><tr style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\"><td style=\"font-size:100%;font-family:'Arial';line-height:1.65;display:block!important;clear:both!important;max-width:580px!important;margin:0 auto;padding:0\">";
	email=email+"<table style=\"font-size:100%;font-family:'Arial';line-height:1.65;width:100%!important;border-collapse:collapse;margin:0;padding:0\"><tbody><tr style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\"><td align=\"center\" style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\">";
	email=email+"<img src=\"http://vkinfotech.890m.com/logo.png\" alt=\"mAqua\" style=\"font-size:100%;font-family:'Arial';line-height:1.65;max-width:100%;display:block;margin:0 auto 1%;padding:0\" class=\"CToWUd\"></td>";
	email=email+"</tr><tr style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\"><td style=\"font-size:100%;font-family:'Arial';line-height:1.65;background:#f4f4f4;margin:0;padding:30px 35px\" bgcolor=\"#F4F4F4\">";
	email=email+"<h2 style=\"font-size:28px;font-family:'Arial';line-height:1.25;margin:0 0 20px;padding:0\">Hi "+actionForm.getFirstName()+",</h2>";
	email=email+"<p style=\"font-size:16px;font-family:'Arial';line-height:1.65;font-weight:normal;margin:0 0 20px;padding:0\">Thank you for signing up and welcome to mAqua: mobile automation testing solution.</p>";
	email=email+"<p style=\"font-size:16px;font-family:'Arial';line-height:1.65;font-weight:normal;margin:0 0 20px;padding:0\"><strong style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\">Getting Started:</strong> <br style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\">";
	email=email+"The best way to get started with mAqua is to run the demo project provided by mAqua admin.</p>";
	email=email+"<ul style=\"font-size:16px;font-family:'Arial';line-height:1.65;font-weight:normal;margin:0 0 20px;padding:0 0 0 10%\"><li style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\">Sign-in to your account with your Email-ID and password.</li>";
	email=email+"<li style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\">You can select Project, Release, environment,Sprint,Testing, Platform, Executed on and by filters to see respective report </li>"+
          "<li style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\">Click on \"View Scripts\" on sidebar to see the scripts for the respective project.</li>"+
          "<li style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\">Click on \"Schedule or Run\" on sidebar to run or schedule a test against vast variety of devices</li>"+
          "<li style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\">Click on \"Reports\" on sidebar to see history reports and test analytic</li>"+
          "<li style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\">Click on \"Manage project\" on sidebar to add project, resource location etc.</li>";
	email=email+"</ul><p style=\"font-size:16px;font-family:'Arial';line-height:1.65;font-weight:normal;margin:0 0 20px;padding:0\"><strong style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\">You are all set to run your first test.</strong></p>"+
				"<table style=\"font-size:100%;font-family:'Arial';line-height:1.65;width:100%!important;border-collapse:collapse;margin:0;padding:0\"><tbody><tr style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\"><td align=\"center\" style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\">"+
				"<p style=\"font-size:16px;font-family:'Arial';line-height:1.65;font-weight:normal;margin:0 0 20px;padding:0\">";
	email=email+"<a href=\"http://localhost:8080/mAquaConsole/verrify@link.do?token="+verficationCode+"&tokenid="+md5OfUserid+"\" style=\"font-size:100%;font-family:'Arial';line-height:1.65;color:white;text-decoration:none;display:inline-block;font-weight:bold;border-radius:4px;background:#3399ff;margin:0;padding:0;border-color:#3399ff;border-style:solid;border-width:10px 20px 8px\" target=\"_blank\">Get Started Now</a>";
	email=email+"</p></td></tr></tbody></table><p style=\"font-size:16px;font-family:'Arial';line-height:1.65;font-weight:normal;margin:0 0 20px;padding:0\"><strong style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\">Need assistance?</strong> Simply reply to this email and our amazing support team is here to help you.</p>";
	email=email+"<p style=\"font-size:16px;font-family:'Arial';line-height:1.65;font-weight:normal;margin:0 0 20px;padding:0\"><em style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\">Best,</em><br style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\">"+
			"The mAqua team<br style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\">"+
			"mobile automation testing solution.<br style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\">"+
			"<a href=\"mailto:support@beaconstream.com\" target=\"_blank\">support@beaconstream.com</a><br style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\">"+
			"480-951-4407<br style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\"><a href=\"http://www.beaconstream.com\" style=\"font-size:100%;font-family:'Arial';line-height:1.65;color:#71bc37;text-decoration:none;margin:0;padding:0\" target=\"_blank\">www.beaconstream.com</a></p>";
	email=email+"</td> </tr></tbody></table></td></tr><tr style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\"><td style=\"font-size:100%;font-family:'Arial';line-height:1.65;display:block!important;clear:both!important;max-width:580px!important;margin:0 auto;padding:0\">";
	email=email+"<table style=\"font-size:100%;font-family:'Arial';line-height:1.65;width:100%!important;border-collapse:collapse;margin:0;padding:0\"><tbody><tr style=\"font-size:100%;font-family:'Arial';line-height:1.65;margin:0;padding:0\"><td align=\"center\" style=\"font-size:100%;font-family:'Arial';line-height:1.65;background:white none;margin:0;padding:30px 35px\" bgcolor=\"white\">"+
			"<p style=\"font-size:14px;font-family:'Arial';line-height:1.65;font-weight:normal;color:#888;text-align:center;margin:0;padding:0\" align=\"center\">Sent by <a href=\"http://www.beaconstream.com\" style=\"font-size:100%;font-family:'Arial';line-height:1.65;color:#888;text-decoration:none;font-weight:bold;margin:0;padding:0\" target=\"_blank\">BeaconStream</a>, 114301 N. 87th Street, Suite 110 Scottsdale, AZ 85260, USA</p>";
	email=email+"</td></tr></tbody></table></td></tr></tbody></table></div></div></div></div>";
*/
 }

